server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    driver-class-name: ${jdbc.driver}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
  thymeleaf:
    cache: false




mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.edu.whut.androidmonitor.entity
  configuration:
    map-underscore-to-camel-case: true